### ISSUE TITLE
Redundant redefination of "CNN-model" in step4_test_classifier.py file

### ISSUE THREAD

**Issue by rednafi** [suhailnajeeb/retinal-oct-classify#1]
You redefined the model that you used for **training** again in the **test** (step4_test_classifier.py) file.  You can solve it via saving the whole **model**  using `model.save('cnn_model.h5')`  during **training** instead of just the **weights**  and reloading it again using `load_model(cnn_model.h5')`. 

full code:

```
from keras.models import load_model

""" run this in your train.py file. 
     creating a HDF5 file 'cnn_model.h5' (this includes weights + architecture) """
model.save('cnn_model.h5')  
del model  

""" run this in the step4_test_classifier.py file """
model = load_model('cnn_model.h5')
```

**Comment by suhailnajeeb** [comment]
Thanks. I know this. Bacchakaaler code 😛

**Comment by rednafi** [comment]
Then I'm closing this issue. Since this redundancy does not break anything. Thanks!
